steps:
  # Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nasa-gt-api', '.']
  
  # Push a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nasa-gt-api']
  
  # Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'nasa-gt-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/nasa-gt-api'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '300'